### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by thierry-FreeBSD** [c-koi/libboard#1]
Hello,

Is this project the official replacement of http://libboard.sourceforge.net/ ?

Any release scheduled?

Thanks.

**Comment by c-koi** [comment]
Hi,

Yes, this is the (new) official repository for libboard.
No release is scheduled right now, even though there have been quite a few changes lately (bitmap images, bug fixes, tilings & append methods, etc.)

**Comment by thierry-FreeBSD** [comment]
Thanks. I've just updated the FreeBSD port with this info:
http://www.freshports.org/graphics/libboard/
